테스트 메서드에서 예외가 발생하건 말건 tearDown()이 호출되도록 보장해 주는 기능을 구현하려ㅑ고 했다.
하지만 테스트가 작동하도록 하려면 예외를 잡아야 한다. (그걸 알기에 시도했다가 다시 빼 버렸다)
만약 이 기능을 구현하다가 실수하면 예외가 보고되지 않기 때문에, 실수를 알아챌 방법이 없다.

일반적으로 테스트를 구현하는 순서는 중요하다. 다음에 테스트를 선택할 때, 가르침을 줄 수 있고 만들 수 있다는 확신이 드는 것을 선택한다.
만약 테스트를 하나 성공시켰는데 그 다음 테스트를 만들며 문제가 생기면 난 두 단계 뒤로 물러서는 것을 고려한다.

---
**검토**
- 가짜 구현을 한 뒤에 단계적으로 상수를 변수로 바꾸어 실제 구현으로 만들었다.
- 또 다른 테스트를 작성했다.
- 테스트가 실패했을 때 좀 더 작은 스케일로 또 다른 테스트를 만들어서 실패한 테스트가 성공하게 만드는 것을 보조할 수 있었다.
